/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as AppReposRepoIdRouteImport } from './routes/_app/repos.$repoId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppReposRepoIdIndexRouteImport } from './routes/_app/repos.$repoId.index'
import { Route as AppReposRepoIdBranchesSplatRouteImport } from './routes/_app/repos.$repoId.branches.$'
import { Route as AppReposRepoIdPullsNumberRouteImport } from './routes/_app/repos.$repoId.pulls.$number'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppReposRepoIdRoute = AppReposRepoIdRouteImport.update({
  id: '/repos/$repoId',
  path: '/repos/$repoId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReposRepoIdIndexRoute = AppReposRepoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReposRepoIdRoute,
} as any)
const AppReposRepoIdBranchesSplatRoute =
  AppReposRepoIdBranchesSplatRouteImport.update({
    id: '/branches/$',
    path: '/branches/$',
    getParentRoute: () => AppReposRepoIdRoute,
  } as any)
const AppReposRepoIdPullsNumberRoute =
  AppReposRepoIdPullsNumberRouteImport.update({
    id: '/pulls/$number',
    path: '/pulls/$number',
    getParentRoute: () => AppReposRepoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/me': typeof AppMeRoute
  '/repos/$repoId': typeof AppReposRepoIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/repos/$repoId/': typeof AppReposRepoIdIndexRoute
  '/repos/$repoId/branches/$': typeof AppReposRepoIdBranchesSplatRoute
  '/repos/$repoId/pulls/$number': typeof AppReposRepoIdPullsNumberRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/me': typeof AppMeRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/repos/$repoId': typeof AppReposRepoIdIndexRoute
  '/repos/$repoId/branches/$': typeof AppReposRepoIdBranchesSplatRoute
  '/repos/$repoId/pulls/$number': typeof AppReposRepoIdPullsNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/me': typeof AppMeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/repos/$repoId': typeof AppReposRepoIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/repos/$repoId/': typeof AppReposRepoIdIndexRoute
  '/_app/repos/$repoId/branches/$': typeof AppReposRepoIdBranchesSplatRoute
  '/_app/repos/$repoId/pulls/$number': typeof AppReposRepoIdPullsNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/me'
    | '/repos/$repoId'
    | '/api/auth/$'
    | '/repos/$repoId/'
    | '/repos/$repoId/branches/$'
    | '/repos/$repoId/pulls/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/me'
    | '/'
    | '/api/auth/$'
    | '/repos/$repoId'
    | '/repos/$repoId/branches/$'
    | '/repos/$repoId/pulls/$number'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/me'
    | '/_app/'
    | '/_app/repos/$repoId'
    | '/api/auth/$'
    | '/_app/repos/$repoId/'
    | '/_app/repos/$repoId/branches/$'
    | '/_app/repos/$repoId/pulls/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repos/$repoId': {
      id: '/_app/repos/$repoId'
      path: '/repos/$repoId'
      fullPath: '/repos/$repoId'
      preLoaderRoute: typeof AppReposRepoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/repos/$repoId/': {
      id: '/_app/repos/$repoId/'
      path: '/'
      fullPath: '/repos/$repoId/'
      preLoaderRoute: typeof AppReposRepoIdIndexRouteImport
      parentRoute: typeof AppReposRepoIdRoute
    }
    '/_app/repos/$repoId/branches/$': {
      id: '/_app/repos/$repoId/branches/$'
      path: '/branches/$'
      fullPath: '/repos/$repoId/branches/$'
      preLoaderRoute: typeof AppReposRepoIdBranchesSplatRouteImport
      parentRoute: typeof AppReposRepoIdRoute
    }
    '/_app/repos/$repoId/pulls/$number': {
      id: '/_app/repos/$repoId/pulls/$number'
      path: '/pulls/$number'
      fullPath: '/repos/$repoId/pulls/$number'
      preLoaderRoute: typeof AppReposRepoIdPullsNumberRouteImport
      parentRoute: typeof AppReposRepoIdRoute
    }
  }
}

interface AppReposRepoIdRouteChildren {
  AppReposRepoIdIndexRoute: typeof AppReposRepoIdIndexRoute
  AppReposRepoIdBranchesSplatRoute: typeof AppReposRepoIdBranchesSplatRoute
  AppReposRepoIdPullsNumberRoute: typeof AppReposRepoIdPullsNumberRoute
}

const AppReposRepoIdRouteChildren: AppReposRepoIdRouteChildren = {
  AppReposRepoIdIndexRoute: AppReposRepoIdIndexRoute,
  AppReposRepoIdBranchesSplatRoute: AppReposRepoIdBranchesSplatRoute,
  AppReposRepoIdPullsNumberRoute: AppReposRepoIdPullsNumberRoute,
}

const AppReposRepoIdRouteWithChildren = AppReposRepoIdRoute._addFileChildren(
  AppReposRepoIdRouteChildren,
)

interface AppRouteChildren {
  AppMeRoute: typeof AppMeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppReposRepoIdRoute: typeof AppReposRepoIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppMeRoute: AppMeRoute,
  AppIndexRoute: AppIndexRoute,
  AppReposRepoIdRoute: AppReposRepoIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
